AddonId: 62ac4052-e08a-4a1a-b70a-c2c0c3673bb9
Packages:
  - Version: 0.3.9
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2025-11-05
    PackageUrl: https://github.com/Dasmius007/HumbleKeysLibrary/releases/download/0.3.9/HumbleKeysLibrary_0.3.9.pext
    Changelog:
      - IMPORTANT - Platform field is no longer used by default for the Redemption Store (i.e. Steam, GOG, etc.), but now Source is (helps some metadata plugins properly match games)
      - Added dropdown setting to add Redemption Store (e.g. Steam) to either Source (now default), Tag, Category, or Platform (no longer default) field, or None (disabled)
      - Added checkbox setting to add Key Redemption status Tag (default enabled)
      - Added checkbox setting to "Add Humble & Steam links" (default enabled)
      - Added checkbox setting to add "Nintendo Switch" to Platform for all Nintendo keys
      - Added checkbox setting to add default of "PC (Windows)" to Platform for all other keys
      - Updated settings UI to be more compact and add the above features
      - Fixed a couple misc. bugs related to key redemption tags and tag methodology
      - Added more logging to help debug excessive library update time reported by some users
  - Version: 0.3.8
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2025-05-07
    PackageUrl: https://github.com/Dasmius007/HumbleKeysLibrary/releases/download/0.3.8/HumbleKeysLibrary_0.3.8.pext
    Changelog:
      - Restored plugin name
      - Restored plugin GUID to fix broken auto-update process from old versions, prevent duplicate old & new plugins installed at the same time, and ensure "Already installed" button works properly in Add-on Browser
  - Version: 0.3.6
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2025-05-04
    PackageUrl: https://github.com/Dasmius007/HumbleKeysLibrary/releases/download/0.3.6/HumbleKeysLibrary_0.3.6.pext
    Changelog:
      - Added support for multiple languages (currently only English is implemented, but other languages can now be added)
      - Language is determined by Windows culture (may add a setting for it later)
      - Fixed missing "Connect account" description next to checkbox
      - Fixed missing "Authenticate" button text
      - Now shows authentication status next to the button like other library add-ons
  - Version: 0.3.4
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2025-03-20
    PackageUrl: https://github.com/Dasmius007/HumbleKeysLibrary/releases/download/0.3.4/HumbleKeysLibrary_0.3.4.pext
    Changelog:
      - Altered how tags are handled to deal with scenario where tags get removed manually via Manage Library function of Playnite
      - Corrected tooltips for Unredeemable key handling
      - Remove prerequisite "Import Choice Game" from "Unredeemable key handling" options
      - Correct github action to build against correct tag version
      - Update ChoiceMonth model to include ChoicesRemaining and ChoicesMade
      - Update Order model to determine virtual orders (items added from Bundle instead of from persisted record on server)
      - Alter HumbleKeysAccountClient to add virtual orders that have not yet been added to the Order
      - Add additional logic to HumbleKeysLibrary to handle unredeemable virtual orders (either expired and cannot be redeemed or part of a Bundle where all choices have been made)
      - Add new option to allow for either tagging a Game as Key "Unredeemable" or not add to the library
      - Correct version number to match release version
      - Added Optional feature to import games in Humble Choice Monthly bundles.
      - Added Optional feature to create tags based on Bundle Names (Either all Bundles or Monthly only)
      - Added Optional feature to cache API Objects as JSON files in the ExtensionsData directory
  - Version: 0.2.0
    RequiredApiVersion: 6.1.8
    ReleaseDate: 2022-06-09
    PackageUrl: https://github.com/Dasmius007/HumbleKeysLibrary/releases/download/0.2.0/62ac4052-e08a-4a1a-b70a-c2c0c3673bb9_0_2_0.pext
    Changelog:
      - 'Updated for new SDK. Also fixes Newtonsoft.Json exceptions thrown when Humble API returns **redeemed_key_val**'
      - 'as a JObject instead of JString.'
      - ''
      - 'Tested against:'
      - 'Playnite 9.18'
      - 'SDK 6.2.2'
      - 'Desktop 2.1.0'
  - Version: 0.1.4
    RequiredApiVersion: 6.1.8
    ReleaseDate: 2020-10-08
    PackageUrl: https://github.com/Dasmius007/HumbleKeysLibrary/releases/download/0.1.4/Humble_Keys_Library_Importer_0_1_4.pext
    Changelog:
      - 'Adds **Ignore Redeemed Keys** setting. When checked, the library does not import any keys which have'
      - 'already been redeemed.'
  - Version: 0.1.3
    RequiredApiVersion: 6.1.8
    ReleaseDate: 2020-10-06
    PackageUrl: https://github.com/Dasmius007/HumbleKeysLibrary/releases/download/0.1.3/Humble_Keys_Library_Importer_0_1_3.pext
    Changelog:
      - 'Compiled for Playnite 8.0'
      - ''
      - 'Removes references to Playnite and Playnite.Common assemblies to comply with SDK changes in Playnite 8.'
  - Version: 0.1.2
    RequiredApiVersion: 6.1.8
    ReleaseDate: 2020-10-02
    PackageUrl: https://github.com/Dasmius007/HumbleKeysLibrary/releases/download/0.1.2/HumbleKeysLibrary_0_1_2.pext
    Changelog:
      - 'Compiled for Playnite 7.9'
      - ''
      - 'Improves key type filtering and adds settings view localization. Also changes "Platform" for keys to reflect the'
      - 'TPKD machine name, as the human names were too inconsistent and creating many single-game platforms.'
  - Version: 0.1.1
    RequiredApiVersion: 6.1.8
    ReleaseDate: 2020-10-01
    PackageUrl: https://github.com/Dasmius007/HumbleKeysLibrary/releases/download/0.1.1/HumbleKeysLibrary_0_1_1.pext
    Changelog:
      - 'Compiled for Playnite 7.9'
      - ''
      - 'Improves key type filtering and adds settings view localization. Also changes "Platform" for keys to reflect the'
      - 'TPKD machine name, as the human names were too inconsistent and creating many single-game platforms.'
  - Version: 0.1.0
    RequiredApiVersion: 6.1.8
    ReleaseDate: 2020-10-01
    PackageUrl: https://github.com/Dasmius007/HumbleKeysLibrary/releases/download/0.1.0/HumbleKeyLibrary_0_1_0.pext
    Changelog:
      - 'Adds **nintendo_direct** tag to Humble key_type whitelist and removes extraneous **Humble Key: {key_type}** tagging,'
      - 'since that information is already in "Platform".'
      - ''
      - ''
      - '# v0.1.0 Pre-release'
      - 'Release v0.1.0'
      - 'Installation'
      - 'Drag and drop the .pext file onto your Playnite window.'
      - ''
      - 'Release Details'
      - 'First release implements:'
      - ''
      - '* Querying the Humble API for "TPKD" objects that represent game keys.'
      - '* Checking against a key type whitelist (currently only permits steam keys)'
      - '* Reporting the Redeemed / Unredeemed status as tags'
      - '* Updates Redeemed / Unredeemed on previously imported games when loading the Humble Keys Library'
      - '* Creates a link to your Humble "downloads" page'
      - ''
      - 'Upcoming features:'
      - ''
      - '* Other key types in the white list'
      - '* Integrating localization'
